version: "3.7"

services:  
    database:
        image: postgres
        container_name: eamusic_container
        restart: always
        ports: 
            - 5432:5432
        environment: 
        - POSTGRES_USER=eamusicadmin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=eamusic
        volumes:
        - pgdata:/data/postgres
           
    app:
        build: .
        container_name: eamusic_container_app
        restart: always
        ports:
            - 3333:3333
            - 9229:9229
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on: 
            - database
        

volumes:
    pgdata:
        driver: local