version: "3.9"

services:
  database:
    image: postgres
    container_name: database_eamusic
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=adminuser
      - POSTGRES_PASSWORD=adminuser
      - POSTGRES_DB=eamusic
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: eamusic
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local